<?php
/**
 * Required Plugins for this theme
 *
 * @package wp_rig
 */

/**
 * Setup suggested plugin system.
 *
 * Include the Austintatious_Design_Plugin_Manager class and add
 * an interface for users to to manage suggested
 * plugins.
 *
 * */

 if( function_exists('acf_add_local_field_group') ):

 	acf_add_local_field_group(array(
 		'key' => 'group_5f61132ea0e4c',
 		'title' => 'Analytics',
 		'fields' => array(
 			array(
 				'key' => 'field_5f611335d4024',
 				'label' => 'google_tag_manager_id',
 				'name' => 'google_tag_manager_id',
 				'type' => 'text',
 				'instructions' => 'This is the Google Tag ID associated with the account',
 				'required' => 0,
 				'conditional_logic' => 0,
 				'wrapper' => array(
 					'width' => '',
 					'class' => '',
 					'id' => '',
 				),
 				'default_value' => '',
 				'placeholder' => 'GTM-NQRF8CC',
 				'prepend' => '',
 				'append' => '',
 				'maxlength' => '',
 			),
 			array(
 				'key' => 'field_5f6114ded4025',
 				'label' => 'facebook_pixel_id',
 				'name' => 'facebook_pixel_id',
 				'type' => 'text',
 				'instructions' => 'Facebook Pixel ID',
 				'required' => 0,
 				'conditional_logic' => 0,
 				'wrapper' => array(
 					'width' => '',
 					'class' => '',
 					'id' => '',
 				),
 				'default_value' => '',
 				'placeholder' => 570168077230923,
 				'prepend' => '',
 				'append' => '',
 				'maxlength' => '',
 			),
 			array(
 				'key' => 'field_5f6116b2d4026',
 				'label' => 'facebook_pixel_triggers',
 				'name' => 'facebook_pixel_triggers',
 				'type' => 'repeater',
 				'instructions' => '',
 				'required' => 0,
 				'conditional_logic' => array(
 					array(
 						array(
 							'field' => 'field_5f6114ded4025',
 							'operator' => '!=empty',
 						),
 					),
 				),
 				'wrapper' => array(
 					'width' => '',
 					'class' => '',
 					'id' => '',
 				),
 				'collapsed' => '',
 				'min' => 0,
 				'max' => 0,
 				'layout' => 'table',
 				'button_label' => '',
 				'sub_fields' => array(
 					array(
 						'key' => 'field_5f6116e4f66a8',
 						'label' => 'trigger_title',
 						'name' => 'trigger_title',
 						'type' => 'text',
 						'instructions' => 'must be unique',
 						'required' => 0,
 						'conditional_logic' => 0,
 						'wrapper' => array(
 							'width' => '',
 							'class' => '',
 							'id' => '',
 						),
 						'default_value' => '',
 						'placeholder' => 'formSubmit',
 						'prepend' => '',
 						'append' => '',
 						'maxlength' => '',
 					),
 					array(
 						'key' => 'field_5f611714f66a9',
 						'label' => 'trigger_selector',
 						'name' => 'trigger_selector',
 						'type' => 'text',
 						'instructions' => 'optional - but is connected to the \'class\' of the element',
 						'required' => 0,
 						'conditional_logic' => 0,
 						'wrapper' => array(
 							'width' => '',
 							'class' => '',
 							'id' => '',
 						),
 						'default_value' => '',
 						'placeholder' => '.ctaButton',
 						'prepend' => '',
 						'append' => '',
 						'maxlength' => '',
 					),
 					array(
 						'key' => 'field_5f611754f66aa',
 						'label' => 'trigger_on',
 						'name' => 'trigger_on',
 						'type' => 'text',
 						'instructions' => 'Trigger action \'on\' (choose between):
 	click
 	amp-form-submit-success',
 						'required' => 0,
 						'conditional_logic' => 0,
 						'wrapper' => array(
 							'width' => '',
 							'class' => '',
 							'id' => '',
 						),
 						'default_value' => '',
 						'placeholder' => 'click',
 						'prepend' => '',
 						'append' => '',
 						'maxlength' => '',
 					),
 					array(
 						'key' => 'field_5f6117c0f66ab',
 						'label' => 'trigger_event_name',
 						'name' => 'trigger_event_name',
 						'type' => 'text',
 						'instructions' => 'This is the description associated with the trigger',
 						'required' => 0,
 						'conditional_logic' => 0,
 						'wrapper' => array(
 							'width' => '',
 							'class' => '',
 							'id' => '',
 						),
 						'default_value' => '',
 						'placeholder' => 'Learn More X button click',
 						'prepend' => '',
 						'append' => '',
 						'maxlength' => '',
 					),
 				),
			 ),
			 array(
				'key' => 'field_5fbd664b8c6c7',
				'label' => 'extra tracking scripts',
				'name' => 'extra_tracking_scripts',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => '',
				'min' => 0,
				'max' => 0,
				'layout' => 'table',
				'button_label' => '',
				'sub_fields' => array(
					array(
						'key' => 'field_5fbd66708c6c8',
						'label' => 'extra tracking script',
						'name' => 'extra_tracking_script',
						'type' => 'textarea',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'maxlength' => '',
						'rows' => '',
						'new_lines' => '',
					),
				),
			),
 		),
 		'location' => array(
 			array(
 				array(
 					'param' => 'post_type',
 					'operator' => '==',
 					'value' => 'analytics',
 				),
 			),
 		),
 		'menu_order' => 0,
 		'position' => 'normal',
 		'style' => 'default',
 		'label_placement' => 'top',
 		'instruction_placement' => 'label',
 		'hide_on_screen' => '',
 		'active' => true,
 		'description' => '',
 	));

 	acf_add_local_field_group(array(
 		'key' => 'group_5f456f8ece332',
 		'title' => 'Block Hook',
 		'fields' => array(
 			array(
 				'key' => 'field_5f4570eb8bcf2',
 				'label' => 'Card Block',
 				'name' => 'card_block',
 				'type' => 'repeater',
 				'instructions' => '',
 				'required' => 0,
 				'conditional_logic' => 0,
 				'wrapper' => array(
 					'width' => '',
 					'class' => '',
 					'id' => '',
 				),
 				'collapsed' => '',
 				'min' => 0,
 				'max' => 0,
 				'layout' => 'table',
 				'button_label' => '',
 				'sub_fields' => array(
 					array(
 						'key' => 'field_5f4571208bcf3',
 						'label' => 'card_content',
 						'name' => 'card_content',
 						'type' => 'wysiwyg',
 						'instructions' => '',
 						'required' => 0,
 						'conditional_logic' => 0,
 						'wrapper' => array(
 							'width' => '',
 							'class' => '',
 							'id' => '',
 						),
 						'default_value' => '',
 						'tabs' => 'all',
 						'toolbar' => 'full',
 						'media_upload' => 1,
 						'delay' => 0,
 					),
 				),
 			),
 			array(
 				'key' => 'field_5f4571ee3bde2',
 				'label' => 'card_block_number',
 				'name' => 'card_block_number',
 				'type' => 'text',
 				'instructions' => 'could be number or letter or combination of both, but must not include spaces AND must be unique',
 				'required' => 1,
 				'conditional_logic' => 0,
 				'wrapper' => array(
 					'width' => '',
 					'class' => '',
 					'id' => '',
 				),
 				'default_value' => '',
 				'placeholder' => 1,
 				'prepend' => '',
 				'append' => '',
 				'maxlength' => '',
 			),
 		),
 		'location' => array(
 			array(
 				array(
 					'param' => 'post_type',
 					'operator' => '==',
 					'value' => 'elements',
 				),
 			),
 		),
 		'menu_order' => 0,
 		'position' => 'normal',
 		'style' => 'default',
 		'label_placement' => 'top',
 		'instruction_placement' => 'label',
 		'hide_on_screen' => '',
 		'active' => true,
 		'description' => '',
 	));

 	acf_add_local_field_group(array(
 		'key' => 'group_5f45783e98990',
 		'title' => 'Block: Testimonial',
 		'fields' => array(
 			array(
 				'key' => 'field_5f45784ddc142',
 				'label' => 'avatar',
 				'name' => 'avatar',
 				'type' => 'image',
 				'instructions' => '',
 				'required' => 0,
 				'conditional_logic' => 0,
 				'wrapper' => array(
 					'width' => '',
 					'class' => '',
 					'id' => '',
 				),
 				'return_format' => 'array',
 				'preview_size' => 'medium',
 				'library' => 'all',
 				'min_width' => '',
 				'min_height' => '',
 				'min_size' => '',
 				'max_width' => '',
 				'max_height' => '',
 				'max_size' => '',
 				'mime_types' => '',
 			),
 			array(
 				'key' => 'field_5f457862dc143',
 				'label' => 'author',
 				'name' => 'author',
 				'type' => 'text',
 				'instructions' => '',
 				'required' => 0,
 				'conditional_logic' => 0,
 				'wrapper' => array(
 					'width' => '',
 					'class' => '',
 					'id' => '',
 				),
 				'default_value' => '',
 				'placeholder' => '',
 				'prepend' => '',
 				'append' => '',
 				'maxlength' => '',
 			),
 			array(
 				'key' => 'field_5f457872dc144',
 				'label' => 'Testimonial',
 				'name' => 'testimonial',
 				'type' => 'textarea',
 				'instructions' => '',
 				'required' => 0,
 				'conditional_logic' => 0,
 				'wrapper' => array(
 					'width' => '',
 					'class' => '',
 					'id' => '',
 				),
 				'default_value' => '',
 				'placeholder' => '',
 				'maxlength' => '',
 				'rows' => '',
 				'new_lines' => '',
 			),
 			array(
 				'key' => 'field_5f45788bdc145',
 				'label' => 'Background Color',
 				'name' => 'background_color',
 				'type' => 'color_picker',
 				'instructions' => '',
 				'required' => 0,
 				'conditional_logic' => 0,
 				'wrapper' => array(
 					'width' => '',
 					'class' => '',
 					'id' => '',
 				),
 				'default_value' => '',
 			),
 			array(
 				'key' => 'field_5f4578a7dc146',
 				'label' => 'Text Color',
 				'name' => 'text_color',
 				'type' => 'color_picker',
 				'instructions' => '',
 				'required' => 0,
 				'conditional_logic' => 0,
 				'wrapper' => array(
 					'width' => '',
 					'class' => '',
 					'id' => '',
 				),
 				'default_value' => '',
 			),
 		),
 		'location' => array(
 			array(
 				array(
 					'param' => 'block',
 					'operator' => '==',
 					'value' => 'acf/testimonial',
 				),
 			),
 		),
 		'menu_order' => 0,
 		'position' => 'normal',
 		'style' => 'default',
 		'label_placement' => 'top',
 		'instruction_placement' => 'label',
 		'hide_on_screen' => '',
 		'active' => true,
 		'description' => '',
 	));

 	acf_add_local_field_group(array(
 		'key' => 'group_5f773f78048c2',
 		'title' => 'CardsBlock',
 		'fields' => array(
 			array(
 				'key' => 'field_5f773fa187d25',
 				'label' => 'card_title',
 				'name' => 'card_title',
 				'type' => 'text',
 				'instructions' => '',
 				'required' => 0,
 				'conditional_logic' => 0,
 				'wrapper' => array(
 					'width' => '',
 					'class' => '',
 					'id' => '',
 				),
 				'default_value' => '',
 				'placeholder' => '',
 				'prepend' => '',
 				'append' => '',
 				'maxlength' => '',
 			),
 			array(
 				'key' => 'field_5f773fb787d26',
 				'label' => 'card_subtitle',
 				'name' => 'card_subtitle',
 				'type' => 'text',
 				'instructions' => '',
 				'required' => 0,
 				'conditional_logic' => 0,
 				'wrapper' => array(
 					'width' => '',
 					'class' => '',
 					'id' => '',
 				),
 				'default_value' => '',
 				'placeholder' => '',
 				'prepend' => '',
 				'append' => '',
 				'maxlength' => '',
 			),
 			array(
 				'key' => 'field_5f773fbf87d27',
 				'label' => 'card_content',
 				'name' => 'card_content',
 				'type' => 'text',
 				'instructions' => '',
 				'required' => 0,
 				'conditional_logic' => 0,
 				'wrapper' => array(
 					'width' => '',
 					'class' => '',
 					'id' => '',
 				),
 				'default_value' => '',
 				'placeholder' => '',
 				'prepend' => '',
 				'append' => '',
 				'maxlength' => '',
 			),
 			array(
 				'key' => 'field_5f773fca87d28',
 				'label' => 'card_img',
 				'name' => 'card_img',
 				'type' => 'image',
 				'instructions' => '',
 				'required' => 0,
 				'conditional_logic' => 0,
 				'wrapper' => array(
 					'width' => '',
 					'class' => '',
 					'id' => '',
 				),
 				'return_format' => 'array',
 				'preview_size' => 'medium',
 				'library' => 'all',
 				'min_width' => '',
 				'min_height' => '',
 				'min_size' => '',
 				'max_width' => '',
 				'max_height' => '',
 				'max_size' => '',
 				'mime_types' => '',
 			),
 			array(
 				'key' => 'field_5f773fd087d29',
 				'label' => 'card_cta',
 				'name' => 'card_cta',
 				'type' => 'text',
 				'instructions' => '',
 				'required' => 0,
 				'conditional_logic' => 0,
 				'wrapper' => array(
 					'width' => '',
 					'class' => '',
 					'id' => '',
 				),
 				'default_value' => '',
 				'placeholder' => '',
 				'prepend' => '',
 				'append' => '',
 				'maxlength' => '',
 			),
 			array(
 				'key' => 'field_5f773fdd987be',
 				'label' => 'card_cta_link',
 				'name' => 'card_cta_link',
 				'type' => 'text',
 				'instructions' => '',
 				'required' => 0,
 				'conditional_logic' => 0,
 				'wrapper' => array(
 					'width' => '',
 					'class' => '',
 					'id' => '',
 				),
 				'default_value' => '',
 				'placeholder' => '',
 				'prepend' => '',
 				'append' => '',
 				'maxlength' => '',
 			),
 			array(
 				'key' => 'field_5f774001987bf',
 				'label' => 'card_cta_is_lightbox',
 				'name' => 'card_cta_is_lightbox',
 				'type' => 'text',
 				'instructions' => 'default is empty unless is lightbox then YES',
 				'required' => 0,
 				'conditional_logic' => array(
 					array(
 						array(
 							'field' => 'field_5f773fdd987be',
 							'operator' => '!=empty',
 						),
 					),
 				),
 				'wrapper' => array(
 					'width' => '',
 					'class' => '',
 					'id' => '',
 				),
 				'default_value' => '',
 				'placeholder' => '',
 				'prepend' => '',
 				'append' => '',
 				'maxlength' => '',
			 ),
			 array(
				'key' => 'field_5fc2a59ef227c',
				'label' => 'cta_hero_carousel_number',
				'name' => 'cta_hero_carousel_number',
				'type' => 'number',
				'instructions' => 'If using Carousel Hero Slider link CTA to the specific carousel image here:',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),array(
				'key' => 'field_5fc2a59ef227c',
				'label' => 'cta_hero_carousel_number',
				'name' => 'cta_hero_carousel_number',
				'type' => 'number',
				'instructions' => 'If using Carousel Hero Slider link CTA to the specific carousel image here:',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
 		),
 		'location' => array(
 			array(
 				array(
 					'param' => 'block',
 					'operator' => '==',
 					'value' => 'acf/card-block',
 				),
 			),
 		),
 		'menu_order' => 0,
 		'position' => 'normal',
 		'style' => 'default',
 		'label_placement' => 'top',
 		'instruction_placement' => 'label',
 		'hide_on_screen' => '',
 		'active' => true,
 		'description' => '',
 	));

 	acf_add_local_field_group(array(
 		'key' => 'group_5eed2a6a05dbb',
 		'title' => 'Contact Items',
 		'fields' => array(
 			array(
 				'key' => 'field_5f986e911e55a',
 				'label' => 'business_name',
 				'name' => 'business_name',
 				'type' => 'text',
 				'instructions' => '',
 				'required' => 0,
 				'conditional_logic' => 0,
 				'wrapper' => array(
 					'width' => '',
 					'class' => '',
 					'id' => '',
 				),
 				'default_value' => '',
 				'placeholder' => '',
 				'prepend' => '',
 				'append' => '',
 				'maxlength' => '',
 			),
 			array(
 				'key' => 'field_5eed2a6a098b9',
 				'label' => 'contact_us_phone',
 				'name' => 'contact_us_phone',
 				'type' => 'text',
 				'instructions' => 'This is what is displayed in browser',
 				'required' => 1,
 				'conditional_logic' => 0,
 				'wrapper' => array(
 					'width' => '',
 					'class' => '',
 					'id' => '',
 				),
 				'default_value' => '',
 				'placeholder' => '(512) 722-7222',
 				'prepend' => '',
 				'append' => '',
 				'maxlength' => '',
			 ),
			 array(
				'key' => 'field_5faec6ecd10b5',
				'label' => 'contact_us_phone_title',
				'name' => 'contact_us_phone_title',
				'type' => 'text',
				'instructions' => 'leave blank if not needed',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => 'HELPline',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
 			array(
 				'key' => 'field_5eed2a6a09ca1',
 				'label' => 'contact_us_phone_link',
 				'name' => 'contact_us_phone_link',
 				'type' => 'text',
 				'instructions' => 'all numbers connected as one',
 				'required' => 0,
 				'conditional_logic' => 0,
 				'wrapper' => array(
 					'width' => '',
 					'class' => '',
 					'id' => '',
 				),
 				'default_value' => '',
 				'placeholder' => 5127227222,
 				'prepend' => '',
 				'append' => '',
 				'maxlength' => '',
 			),
 			array(
 				'key' => 'field_5eed2a6a0a083',
 				'label' => 'contact_us_street',
 				'name' => 'contact_us_street',
 				'type' => 'text',
 				'instructions' => '',
 				'required' => 0,
 				'conditional_logic' => 0,
 				'wrapper' => array(
 					'width' => '',
 					'class' => '',
 					'id' => '',
 				),
 				'default_value' => '',
 				'placeholder' => '222 Old Kyle Road',
 				'prepend' => '',
 				'append' => '',
 				'maxlength' => '',
 			),
 			array(
 				'key' => 'field_5eed2a6a0a467',
 				'label' => 'contact_us_street_suite',
 				'name' => 'contact_us_street_suite',
 				'type' => 'text',
 				'instructions' => '',
 				'required' => 0,
 				'conditional_logic' => 0,
 				'wrapper' => array(
 					'width' => '',
 					'class' => '',
 					'id' => '',
 				),
 				'default_value' => '',
 				'placeholder' => 'Suite 100',
 				'prepend' => '',
 				'append' => '',
 				'maxlength' => '',
 			),
 			array(
 				'key' => 'field_5eed2a6a0a84c',
 				'label' => 'contact_us_city',
 				'name' => 'contact_us_city',
 				'type' => 'text',
 				'instructions' => '',
 				'required' => 0,
 				'conditional_logic' => 0,
 				'wrapper' => array(
 					'width' => '',
 					'class' => '',
 					'id' => '',
 				),
 				'default_value' => '',
 				'placeholder' => 'Wimberley',
 				'prepend' => '',
 				'append' => '',
 				'maxlength' => '',
 			),
 			array(
 				'key' => 'field_5eed2a6a0ac34',
 				'label' => 'contact_us_state',
 				'name' => 'contact_us_state',
 				'type' => 'text',
 				'instructions' => '',
 				'required' => 0,
 				'conditional_logic' => 0,
 				'wrapper' => array(
 					'width' => '',
 					'class' => '',
 					'id' => '',
 				),
 				'default_value' => '',
 				'placeholder' => 'TX',
 				'prepend' => '',
 				'append' => '',
 				'maxlength' => '',
 			),
 			array(
 				'key' => 'field_5eed2a6a0b017',
 				'label' => 'contact_us_zip',
 				'name' => 'contact_us_zip',
 				'type' => 'text',
 				'instructions' => '',
 				'required' => 0,
 				'conditional_logic' => 0,
 				'wrapper' => array(
 					'width' => '',
 					'class' => '',
 					'id' => '',
 				),
 				'default_value' => '',
 				'placeholder' => 78676,
 				'prepend' => '',
 				'append' => '',
 				'maxlength' => '',
			 ),
			 array(
				'key' => 'field_5faebee38c8e1',
				'label' => 'Multiple Addresses?',
				'name' => 'physical_and_pobox',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_5faec1398c8e3',
				'label' => 'first_address_title',
				'name' => 'first_address_title',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5faebee38c8e1',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => 'Physical Address',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5faec15f8c8e4',
				'label' => 'second_address_title',
				'name' => 'second_address_title',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5faebee38c8e1',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => 'PO Box',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5faebf4c8c8e2',
				'label' => 'second_contact_us_street',
				'name' => 'second_contact_us_street',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5faebee38c8e1',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '222 Old Kyle Road',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5faec18e8c8e5',
				'label' => 'second_contact_us_street_suite',
				'name' => 'second_contact_us_street_suite',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5faebee38c8e1',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => 'suite 2A',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5faec1ac8c8e6',
				'label' => 'second_contact_us_city',
				'name' => 'second_contact_us_city',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5faebee38c8e1',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => 'Wimberley',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5faec1be8c8e7',
				'label' => 'second_contact_us_state',
				'name' => 'second_contact_us_state',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5faebee38c8e1',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => 'TX',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5faec1d18c8e8',
				'label' => 'second_contact_us_zip',
				'name' => 'second_contact_us_zip',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5faebee38c8e1',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '78676',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5fb2faa818bf1',
				'label' => 'business hours open',
				'name' => 'business_hours_open',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '8:00',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5fb2fac818bf2',
				'label' => 'business hours close at',
				'name' => 'business_hours_close_at',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '17:00',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
 			array(
 				'key' => 'field_5eed2a6a0b3fb',
 				'label' => 'contact_us_open_datetime',
 				'name' => 'contact_us_open_datetime',
 				'type' => 'text',
 				'instructions' => 'Mo - Fr, 7:30-16:30',
 				'required' => 0,
 				'conditional_logic' => 0,
 				'wrapper' => array(
 					'width' => '',
 					'class' => '',
 					'id' => '',
 				),
 				'default_value' => '',
 				'placeholder' => 'Mo - Fr, 7:30-16:30',
 				'prepend' => '',
 				'append' => '',
 				'maxlength' => '',
 			),
 			array(
 				'key' => 'field_5eed2a6a0b7df',
 				'label' => 'contact_us_open_datetime_extra',
 				'name' => 'contact_us_open_datetime_extra',
 				'type' => 'text',
 				'instructions' => 'Fr, 9:00-13:00',
 				'required' => 0,
 				'conditional_logic' => 0,
 				'wrapper' => array(
 					'width' => '',
 					'class' => '',
 					'id' => '',
 				),
 				'default_value' => '',
 				'placeholder' => '',
 				'prepend' => '',
 				'append' => '',
 				'maxlength' => '',
 			),
 			array(
 				'key' => 'field_5eed2a6a0bbcb',
 				'label' => 'contact_us_open_days_times',
 				'name' => 'contact_us_open_days_times',
 				'type' => 'text',
 				'instructions' => 'Monday through Friday -	7:30-16:30',
 				'required' => 0,
 				'conditional_logic' => 0,
 				'wrapper' => array(
 					'width' => '',
 					'class' => '',
 					'id' => '',
 				),
 				'default_value' => '',
 				'placeholder' => 'Monday through Friday -	7:30am - 4:30pm',
 				'prepend' => '',
 				'append' => '',
 				'maxlength' => '',
 			),
 			array(
 				'key' => 'field_5eed2a6a0bfac',
 				'label' => 'contact_us_open_days_times_extra',
 				'name' => 'contact_us_open_days_times_extra',
 				'type' => 'text',
 				'instructions' => 'Friday - 9:00am to 1:00pm',
 				'required' => 0,
 				'conditional_logic' => 0,
 				'wrapper' => array(
 					'width' => '',
 					'class' => '',
 					'id' => '',
 				),
 				'default_value' => '',
 				'placeholder' => '',
 				'prepend' => '',
 				'append' => '',
 				'maxlength' => '',
 			),
 			array(
 				'key' => 'field_5eed2a6a0c392',
 				'label' => 'contact_us_closed',
 				'name' => 'contact_us_closed',
 				'type' => 'text',
 				'instructions' => '',
 				'required' => 0,
 				'conditional_logic' => 0,
 				'wrapper' => array(
 					'width' => '',
 					'class' => '',
 					'id' => '',
 				),
 				'default_value' => '',
 				'placeholder' => 'Saturdays and Sundays',
 				'prepend' => '',
 				'append' => '',
 				'maxlength' => '',
 			),
 			array(
 				'key' => 'field_5eed2a6a0c778',
 				'label' => 'contact_us_form',
 				'name' => 'contact_us_form',
 				'type' => 'text',
 				'instructions' => 'This is the url for the mailmunch landing page',
 				'required' => 0,
 				'conditional_logic' => 0,
 				'wrapper' => array(
 					'width' => '',
 					'class' => '',
 					'id' => '',
 				),
 				'default_value' => '',
 				'placeholder' => '',
 				'prepend' => '',
 				'append' => '',
 				'maxlength' => '',
 			),
 			array(
 				'key' => 'field_5eed2a6a0cb62',
 				'label' => 'cta_loading_image',
 				'name' => 'cta_loading_image',
 				'type' => 'image',
 				'instructions' => '',
 				'required' => 0,
 				'conditional_logic' => 0,
 				'wrapper' => array(
 					'width' => '',
 					'class' => '',
 					'id' => '',
 				),
 				'return_format' => 'array',
 				'preview_size' => 'medium',
 				'library' => 'all',
 				'min_width' => '',
 				'min_height' => '',
 				'min_size' => '',
 				'max_width' => '',
 				'max_height' => '',
 				'max_size' => '',
 				'mime_types' => '',
 			),
 			array(
 				'key' => 'field_5eed2a6a0cf43',
 				'label' => 'social_link_dets',
 				'name' => 'social_link_dets',
 				'type' => 'repeater',
 				'instructions' => '',
 				'required' => 0,
 				'conditional_logic' => 0,
 				'wrapper' => array(
 					'width' => '',
 					'class' => '',
 					'id' => '',
 				),
 				'collapsed' => '',
 				'min' => 0,
 				'max' => 0,
 				'layout' => 'table',
 				'button_label' => '',
 				'sub_fields' => array(
 					array(
 						'key' => 'field_5f650d7fd4c57',
 						'label' => 'social_link',
 						'name' => 'social_link',
 						'type' => 'text',
 						'instructions' => '',
 						'required' => 0,
 						'conditional_logic' => 0,
 						'wrapper' => array(
 							'width' => '',
 							'class' => '',
 							'id' => '',
 						),
 						'default_value' => '',
 						'placeholder' => 'https:facebook.com/',
 						'prepend' => '',
 						'append' => '',
 						'maxlength' => '',
 					),
 					array(
 						'key' => 'field_5f650d9ad4c58',
 						'label' => 'social_icon',
 						'name' => 'social_icon',
 						'type' => 'image',
 						'instructions' => '',
 						'required' => 0,
 						'conditional_logic' => 0,
 						'wrapper' => array(
 							'width' => '',
 							'class' => '',
 							'id' => '',
 						),
 						'return_format' => 'array',
 						'preview_size' => 'thumbnail',
 						'library' => 'all',
 						'min_width' => '',
 						'min_height' => '',
 						'min_size' => '',
 						'max_width' => '',
 						'max_height' => '',
 						'max_size' => '',
 						'mime_types' => '',
 					),
 					array(
 						'key' => 'field_5f650eaba6428',
 						'label' => 'social_label',
 						'name' => 'social_label',
 						'type' => 'text',
 						'instructions' => '',
 						'required' => 0,
 						'conditional_logic' => 0,
 						'wrapper' => array(
 							'width' => '',
 							'class' => '',
 							'id' => '',
 						),
 						'default_value' => '',
 						'placeholder' => 'Facebook',
 						'prepend' => '',
 						'append' => '',
 						'maxlength' => '',
 					),
 				),
 			),
 			array(
 				'key' => 'field_5eed2a6a0e2bc',
 				'label' => 'google_map',
 				'name' => 'google_map',
 				'type' => 'text',
 				'instructions' => '',
 				'required' => 0,
 				'conditional_logic' => 0,
 				'wrapper' => array(
 					'width' => '',
 					'class' => '',
 					'id' => '',
 				),
 				'default_value' => '',
 				'placeholder' => 'https:www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d13821.551221624146!2d-98.0954015!3d29.9970191!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0xc65967ad97ee5722!2sKWVH%2094.1%20FM%20Wimberley%20Valley%20Radio!5e0!3m2!1sen!2sus!4v1580758769500!5m2!1sen!2sus',
 				'prepend' => '',
 				'append' => '',
 				'maxlength' => '',
 			),
 			array(
 				'key' => 'field_5f9868d536cfa',
 				'label' => 'left_footer_grid_title',
 				'name' => 'left_footer_grid_title',
 				'type' => 'text',
 				'instructions' => '',
 				'required' => 0,
 				'conditional_logic' => 0,
 				'wrapper' => array(
 					'width' => '',
 					'class' => '',
 					'id' => '',
 				),
 				'default_value' => '',
 				'placeholder' => '',
 				'prepend' => '',
 				'append' => '',
 				'maxlength' => '',
 			),
 			array(
 				'key' => 'field_5f9868c436cf9',
 				'label' => 'middle_footer_grid_title',
 				'name' => 'middle_footer_grid_title',
 				'type' => 'text',
 				'instructions' => '',
 				'required' => 0,
 				'conditional_logic' => 0,
 				'wrapper' => array(
 					'width' => '',
 					'class' => '',
 					'id' => '',
 				),
 				'default_value' => '',
 				'placeholder' => '',
 				'prepend' => '',
 				'append' => '',
 				'maxlength' => '',
 			),
 			array(
 				'key' => 'field_5f9868bb36cf8',
 				'label' => 'right_footer_grid_title',
 				'name' => 'right_footer_grid_title',
 				'type' => 'text',
 				'instructions' => '',
 				'required' => 0,
 				'conditional_logic' => 0,
 				'wrapper' => array(
 					'width' => '',
 					'class' => '',
 					'id' => '',
 				),
 				'default_value' => '',
 				'placeholder' => '',
 				'prepend' => '',
 				'append' => '',
 				'maxlength' => '',
 			),
 			array(
 				'key' => 'field_5f986c0b3623c',
 				'label' => 'contact_footer_background_color',
 				'name' => 'contact_footer_background_color',
 				'type' => 'color_picker',
 				'instructions' => '',
 				'required' => 0,
 				'conditional_logic' => 0,
 				'wrapper' => array(
 					'width' => '',
 					'class' => '',
 					'id' => '',
 				),
 				'default_value' => '',
 			),
 			array(
 				'key' => 'field_5f986c1b3623d',
 				'label' => 'contact_footer_text_color',
 				'name' => 'contact_footer_text_color',
 				'type' => 'color_picker',
 				'instructions' => '',
 				'required' => 0,
 				'conditional_logic' => 0,
 				'wrapper' => array(
 					'width' => '',
 					'class' => '',
 					'id' => '',
 				),
 				'default_value' => '',
 			),
 			array(
 				'key' => 'field_5f986c3d3623e',
 				'label' => 'contact_footer_link_color',
 				'name' => 'contact_footer_link_color',
 				'type' => 'color_picker',
 				'instructions' => '',
 				'required' => 0,
 				'conditional_logic' => 0,
 				'wrapper' => array(
 					'width' => '',
 					'class' => '',
 					'id' => '',
 				),
 				'default_value' => '',
 			),
 		),
 		'location' => array(
 			array(
 				array(
 					'param' => 'post_type',
 					'operator' => '==',
 					'value' => 'contact_items',
 				),
 			),
 		),
 		'menu_order' => 0,
 		'position' => 'normal',
 		'style' => 'default',
 		'label_placement' => 'top',
 		'instruction_placement' => 'label',
 		'hide_on_screen' => '',
 		'active' => true,
 		'description' => '',
 	));

 	acf_add_local_field_group(array(
 		'key' => 'group_5f493ae32e8a6',
 		'title' => 'CTA Hero Links',
 		'fields' => array(
 			array(
 				'key' => 'field_5f493ae3330fb',
 				'label' => 'ctahero_cta_text',
 				'name' => 'ctahero_cta_text',
 				'type' => 'text',
 				'instructions' => '',
 				'required' => 0,
 				'conditional_logic' => array(
 					array(
 						array(
 							'field' => 'field_5f493ae335046',
 							'operator' => '==',
 							'value' => '1',
 						),
 					),
 				),
 				'wrapper' => array(
 					'width' => '',
 					'class' => '',
 					'id' => '',
 				),
 				'default_value' => 'Get A Free Quote',
 				'placeholder' => '',
 				'prepend' => '',
 				'append' => '',
 				'maxlength' => '',
			 ),
			 array(
				'key' => 'field_5f493ae335046',
				'label' => 'cta_in_hero',
				'name' => 'cta_in_hero',
				'type' => 'true_false',
				'instructions' => 'Is this CTA to be displayed in the hero section of the website?',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
 			array(
 				'key' => 'field_5f493ae33353d',
 				'label' => 'ctahero_cta_text_not_hero',
 				'name' => 'ctahero_cta_text_not_hero',
 				'type' => 'text',
 				'instructions' => '',
 				'required' => 0,
 				'conditional_logic' => array(
 					array(
 						array(
 							'field' => 'field_5f493ae335046',
 							'operator' => '!=',
 							'value' => '1',
 						),
 					),
 				),
 				'wrapper' => array(
 					'width' => '',
 					'class' => '',
 					'id' => '',
 				),
 				'default_value' => 'Get A Free Quote',
 				'placeholder' => '',
 				'prepend' => '',
 				'append' => '',
 				'maxlength' => '',
 			),
 			array(
 				'key' => 'field_5f493ae333900',
 				'label' => 'ctahero_cta_url',
 				'name' => 'ctahero_cta_url',
 				'type' => 'text',
 				'instructions' => '',
 				'required' => 0,
 				'conditional_logic' => array(
 					array(
 						array(
 							'field' => 'field_5f493ae335046',
 							'operator' => '==',
 							'value' => '1',
 						),
 					),
 				),
 				'wrapper' => array(
 					'width' => '',
 					'class' => '',
 					'id' => '',
 				),
 				'default_value' => '',
 				'placeholder' => '',
 				'prepend' => '',
 				'append' => '',
 				'maxlength' => '',
 			),
 			array(
 				'key' => 'field_5f493ae333cee',
 				'label' => 'ctahero_cta_url_not_hero',
 				'name' => 'ctahero_cta_url_not_hero',
 				'type' => 'text',
 				'instructions' => '',
 				'required' => 0,
 				'conditional_logic' => array(
 					array(
 						array(
 							'field' => 'field_5f493ae335046',
 							'operator' => '!=',
 							'value' => '1',
 						),
 					),
 				),
 				'wrapper' => array(
 					'width' => '',
 					'class' => '',
 					'id' => '',
 				),
 				'default_value' => '',
 				'placeholder' => '',
 				'prepend' => '',
 				'append' => '',
 				'maxlength' => '',
 			),
 			array(
 				'key' => 'field_5f493ae3340f0',
 				'label' => 'cta_loading_image',
 				'name' => 'cta_loading_image',
 				'type' => 'image',
 				'instructions' => '',
 				'required' => 0,
 				'conditional_logic' => array(
 					array(
 						array(
 							'field' => 'field_5f493ae335046',
 							'operator' => '==',
 							'value' => '1',
 						),
 					),
 				),
 				'wrapper' => array(
 					'width' => '',
 					'class' => '',
 					'id' => '',
 				),
 				'return_format' => 'array',
 				'preview_size' => 'thumbnail',
 				'library' => 'all',
 				'min_width' => '',
 				'min_height' => '',
 				'min_size' => '',
 				'max_width' => '',
 				'max_height' => '',
 				'max_size' => '',
 				'mime_types' => '',
 			),
 			array(
 				'key' => 'field_5f493ae334476',
 				'label' => 'cta_loading_image_not_hero',
 				'name' => 'cta_loading_image_not_hero',
 				'type' => 'image',
 				'instructions' => '',
 				'required' => 0,
 				'conditional_logic' => array(
 					array(
 						array(
 							'field' => 'field_5f493ae335046',
 							'operator' => '!=',
 							'value' => '1',
 						),
 					),
 				),
 				'wrapper' => array(
 					'width' => '',
 					'class' => '',
 					'id' => '',
 				),
 				'return_format' => 'array',
 				'preview_size' => 'thumbnail',
 				'library' => 'all',
 				'min_width' => '',
 				'min_height' => '',
 				'min_size' => '',
 				'max_width' => '',
 				'max_height' => '',
 				'max_size' => '',
 				'mime_types' => '',
 			),
 			array(
 				'key' => 'field_5f493ae3348bb',
 				'label' => 'cta_unique_id',
 				'name' => 'cta_unique_id',
 				'type' => 'text',
 				'instructions' => 'This ID needs to be unique for the purpose of shortcode application. All lowercase_use_underscores_letters_and_or_numbers_only',
 				'required' => 1,
 				'conditional_logic' => array(
 					array(
 						array(
 							'field' => 'field_5f493ae335046',
 							'operator' => '==',
 							'value' => '1',
 						),
 					),
 				),
 				'wrapper' => array(
 					'width' => '',
 					'class' => '',
 					'id' => '',
 				),
 				'default_value' => '',
 				'placeholder' => 'cta_1',
 				'prepend' => '',
 				'append' => '',
 				'maxlength' => '',
 			),
 			array(
 				'key' => 'field_5f493ae334c75',
 				'label' => 'cta_unique_id_not_hero',
 				'name' => 'cta_unique_id_not_hero',
 				'type' => 'text',
 				'instructions' => 'This ID needs to be unique for the purpose of shortcode application. All lowercase_use_underscores_letters_and_or_numbers_only',
 				'required' => 1,
 				'conditional_logic' => array(
 					array(
 						array(
 							'field' => 'field_5f493ae335046',
 							'operator' => '!=',
 							'value' => '1',
 						),
 					),
 				),
 				'wrapper' => array(
 					'width' => '',
 					'class' => '',
 					'id' => '',
 				),
 				'default_value' => '',
 				'placeholder' => 'cta_1',
 				'prepend' => '',
 				'append' => '',
 				'maxlength' => '',
 			),
 			array(
 				'key' => 'field_5f982bd747f4c',
 				'label' => 'cta_lightbox_toggle',
 				'name' => 'cta_lightbox_toggle',
 				'type' => 'true_false',
 				'instructions' => 'Is this CTA to be opened in a lightbox?',
 				'required' => 0,
 				'conditional_logic' => array(
 					array(
 						array(
 							'field' => 'field_5f493ae335046',
 							'operator' => '==',
 							'value' => '1',
 						),
 					),
 				),
 				'wrapper' => array(
 					'width' => '',
 					'class' => '',
 					'id' => '',
 				),
 				'message' => '',
 				'default_value' => 0,
 				'ui' => 0,
 				'ui_on_text' => '',
 				'ui_off_text' => '',
 			),
 			array(
 				'key' => 'field_5f982bf647f4d',
 				'label' => 'cta_lightbox_toggle_not_hero',
 				'name' => 'cta_lightbox_toggle_not_hero',
 				'type' => 'true_false',
 				'instructions' => 'Is this CTA to be opened in a lightbox?',
 				'required' => 0,
 				'conditional_logic' => array(
 					array(
 						array(
 							'field' => 'field_5f493ae335046',
 							'operator' => '!=',
 							'value' => '1',
 						),
 					),
 				),
 				'wrapper' => array(
 					'width' => '',
 					'class' => '',
 					'id' => '',
 				),
 				'message' => '',
 				'default_value' => 0,
 				'ui' => 0,
 				'ui_on_text' => '',
 				'ui_off_text' => '',
 			),
 			array(
 				'key' => 'field_5f49688e91350',
 				'label' => 'cta_color',
 				'name' => 'cta_color',
 				'type' => 'color_picker',
 				'instructions' => '',
 				'required' => 0,
 				'conditional_logic' => array(
 					array(
 						array(
 							'field' => 'field_5f493ae335046',
 							'operator' => '==',
 							'value' => '1',
 						),
 					),
 				),
 				'wrapper' => array(
 					'width' => '',
 					'class' => '',
 					'id' => '',
 				),
 				'default_value' => '',
 			),
 			array(
 				'key' => 'field_5f49690115c5f',
 				'label' => 'cta_color_not_hero',
 				'name' => 'cta_color_not_hero',
 				'type' => 'color_picker',
 				'instructions' => '',
 				'required' => 0,
 				'conditional_logic' => array(
 					array(
 						array(
 							'field' => 'field_5f493ae335046',
 							'operator' => '!=',
 							'value' => '1',
 						),
 					),
 				),
 				'wrapper' => array(
 					'width' => '',
 					'class' => '',
 					'id' => '',
 				),
 				'default_value' => '',
 			),
 			array(
 				'key' => 'field_5f49691f15c60',
 				'label' => 'cta_text_color',
 				'name' => 'cta_text_color',
 				'type' => 'color_picker',
 				'instructions' => '',
 				'required' => 0,
 				'conditional_logic' => array(
 					array(
 						array(
 							'field' => 'field_5f493ae335046',
 							'operator' => '==',
 							'value' => '1',
 						),
 					),
 				),
 				'wrapper' => array(
 					'width' => '',
 					'class' => '',
 					'id' => '',
 				),
 				'default_value' => '',
 			),
 			array(
 				'key' => 'field_5f49693615c61',
 				'label' => 'cta_text_color_not_hero',
 				'name' => 'cta_text_color_not_hero',
 				'type' => 'color_picker',
 				'instructions' => '',
 				'required' => 0,
 				'conditional_logic' => array(
 					array(
 						array(
 							'field' => 'field_5f493ae335046',
 							'operator' => '!=',
 							'value' => '1',
 						),
 					),
 				),
 				'wrapper' => array(
 					'width' => '',
 					'class' => '',
 					'id' => '',
 				),
 				'default_value' => '',
			 ),
 		),
 		'location' => array(
 			array(
 				array(
 					'param' => 'post_type',
 					'operator' => '==',
 					'value' => 'cta_links',
 				),
 			),
 		),
 		'menu_order' => 0,
 		'position' => 'normal',
 		'style' => 'default',
 		'label_placement' => 'top',
 		'instruction_placement' => 'label',
 		'hide_on_screen' => '',
 		'active' => true,
 		'description' => '',
 	));

 	acf_add_local_field_group(array(
 		'key' => 'group_5f45747ccce06',
 		'title' => 'Element Block',
 		'fields' => array(
 			array(
 				'key' => 'field_5f4574aabe091',
 				'label' => 'block_title',
 				'name' => 'block_title',
 				'type' => 'text',
 				'instructions' => '',
 				'required' => 0,
 				'conditional_logic' => 0,
 				'wrapper' => array(
 					'width' => '',
 					'class' => '',
 					'id' => '',
 				),
 				'default_value' => '',
 				'placeholder' => '',
 				'prepend' => '',
 				'append' => '',
 				'maxlength' => '',
 			),
 			array(
 				'key' => 'field_5f457482be090',
 				'label' => 'block_image',
 				'name' => 'block_image',
 				'type' => 'image',
 				'instructions' => '',
 				'required' => 0,
 				'conditional_logic' => 0,
 				'wrapper' => array(
 					'width' => '',
 					'class' => '',
 					'id' => '',
 				),
 				'return_format' => 'array',
 				'preview_size' => 'medium',
 				'library' => 'all',
 				'min_width' => '',
 				'min_height' => '',
 				'min_size' => '',
 				'max_width' => '',
 				'max_height' => '',
 				'max_size' => '',
 				'mime_types' => '',
 			),
 		),
 		'location' => array(
 			array(
 				array(
 					'param' => 'block',
 					'operator' => '==',
 					'value' => 'acf/testimonial',
 				),
 			),
 		),
 		'menu_order' => 0,
 		'position' => 'normal',
 		'style' => 'default',
 		'label_placement' => 'top',
 		'instruction_placement' => 'label',
 		'hide_on_screen' => '',
 		'active' => true,
 		'description' => '',
 	));

 	acf_add_local_field_group(array(
 		'key' => 'group_5eceb8453d4a9',
 		'title' => 'Guest Reviews Block',
 		'fields' => array(
 			array(
 				'key' => 'field_5eceb85263152',
 				'label' => 'testimonial_block_title',
 				'name' => 'testimonial_block_title',
 				'type' => 'text',
 				'instructions' => '',
 				'required' => 0,
 				'conditional_logic' => 0,
 				'wrapper' => array(
 					'width' => '',
 					'class' => '',
 					'id' => '',
 				),
 				'default_value' => 'Guest Reviews',
 				'placeholder' => '',
 				'prepend' => '',
 				'append' => '',
 				'maxlength' => '',
 			),
 			array(
 				'key' => 'field_5eceb87363153',
 				'label' => 'testimonial_block_background_image',
 				'name' => 'testimonial_block_background_image',
 				'type' => 'image',
 				'instructions' => '',
 				'required' => 0,
 				'conditional_logic' => 0,
 				'wrapper' => array(
 					'width' => '',
 					'class' => '',
 					'id' => '',
 				),
 				'return_format' => 'array',
 				'preview_size' => 'medium',
 				'library' => 'all',
 				'min_width' => '',
 				'min_height' => '',
 				'min_size' => '',
 				'max_width' => '',
 				'max_height' => '',
 				'max_size' => '',
 				'mime_types' => '',
 			),
 		),
 		'location' => array(
 			array(
 				array(
 					'param' => 'page',
 					'operator' => '==',
 					'value' => '1453',
 				),
 			),
 		),
 		'menu_order' => 0,
 		'position' => 'normal',
 		'style' => 'default',
 		'label_placement' => 'top',
 		'instruction_placement' => 'label',
 		'hide_on_screen' => '',
 		'active' => true,
 		'description' => '',
 	));

 	acf_add_local_field_group(array(
 		'key' => 'group_5d66c60bb74f5',
 		'title' => 'Hero Images',
 		'fields' => array(
 			array(
 				'key' => 'field_5f98750da6921',
 				'label' => 'hero_carousel_h1',
 				'name' => 'hero_carousel_h1',
 				'type' => 'text',
 				'instructions' => '',
 				'required' => 0,
 				'conditional_logic' => 0,
 				'wrapper' => array(
 					'width' => '',
 					'class' => '',
 					'id' => '',
 				),
 				'default_value' => '',
 				'placeholder' => '',
 				'prepend' => '',
 				'append' => '',
 				'maxlength' => '',
 			),
 			array(
 				'key' => 'field_5f987516a6922',
 				'label' => 'hero_carousel_h2',
 				'name' => 'hero_carousel_h2',
 				'type' => 'text',
 				'instructions' => '',
 				'required' => 0,
 				'conditional_logic' => 0,
 				'wrapper' => array(
 					'width' => '',
 					'class' => '',
 					'id' => '',
 				),
 				'default_value' => '',
 				'placeholder' => '',
 				'prepend' => '',
 				'append' => '',
 				'maxlength' => '',
 			),
 			array(
 				'key' => 'field_5f987522a6923',
 				'label' => 'hero_carousel_text_color',
 				'name' => 'hero_carousel_text_color',
 				'type' => 'color_picker',
 				'instructions' => '',
 				'required' => 0,
 				'conditional_logic' => 0,
 				'wrapper' => array(
 					'width' => '',
 					'class' => '',
 					'id' => '',
 				),
 				'default_value' => '',
 			),
 			array(
 				'key' => 'field_5f98752fa6924',
 				'label' => 'hero_carousel_text_shadow_color',
 				'name' => 'hero_carousel_text_shadow_color',
 				'type' => 'color_picker',
 				'instructions' => '',
 				'required' => 0,
 				'conditional_logic' => 0,
 				'wrapper' => array(
 					'width' => '',
 					'class' => '',
 					'id' => '',
 				),
 				'default_value' => '',
 			),
 			array(
 				'key' => 'field_5f987573a6929',
 				'label' => 'hero_has_button',
 				'name' => 'hero_has_button',
 				'type' => 'true_false',
 				'instructions' => '',
 				'required' => 0,
 				'conditional_logic' => 0,
 				'wrapper' => array(
 					'width' => '',
 					'class' => '',
 					'id' => '',
 				),
 				'message' => '',
 				'default_value' => 0,
 				'ui' => 0,
 				'ui_on_text' => '',
 				'ui_off_text' => '',
 			),
 			array(
 				'key' => 'field_5f98753ca6925',
 				'label' => 'hero_carousel_button_text',
 				'name' => 'hero_carousel_button_text',
 				'type' => 'text',
 				'instructions' => '',
 				'required' => 0,
 				'conditional_logic' => array(
 					array(
 						array(
 							'field' => 'field_5f987573a6929',
 							'operator' => '==',
 							'value' => '1',
 						),
 					),
 				),
 				'wrapper' => array(
 					'width' => '',
 					'class' => '',
 					'id' => '',
 				),
 				'default_value' => '',
 				'placeholder' => '',
 				'prepend' => '',
 				'append' => '',
 				'maxlength' => '',
 			),
 			array(
 				'key' => 'field_5f98754ba6926',
 				'label' => 'hero_carousel_button_link',
 				'name' => 'hero_carousel_button_link',
 				'type' => 'text',
 				'instructions' => '',
 				'required' => 0,
 				'conditional_logic' => array(
 					array(
 						array(
 							'field' => 'field_5f987573a6929',
 							'operator' => '==',
 							'value' => '1',
 						),
 					),
 				),
 				'wrapper' => array(
 					'width' => '',
 					'class' => '',
 					'id' => '',
 				),
 				'default_value' => '',
 				'placeholder' => '',
 				'prepend' => '',
 				'append' => '',
 				'maxlength' => '',
 			),
 			array(
 				'key' => 'field_5f987559a6927',
 				'label' => 'hero_carousel_button_color',
 				'name' => 'hero_carousel_button_color',
 				'type' => 'color_picker',
 				'instructions' => '',
 				'required' => 0,
 				'conditional_logic' => array(
 					array(
 						array(
 							'field' => 'field_5f987573a6929',
 							'operator' => '==',
 							'value' => '1',
 						),
 					),
 				),
 				'wrapper' => array(
 					'width' => '',
 					'class' => '',
 					'id' => '',
 				),
 				'default_value' => '',
 			),
 			array(
 				'key' => 'field_5f987566a6928',
 				'label' => 'hero_carousel_button_text_color',
 				'name' => 'hero_carousel_button_text_color',
 				'type' => 'color_picker',
 				'instructions' => '',
 				'required' => 0,
 				'conditional_logic' => array(
 					array(
 						array(
 							'field' => 'field_5f987573a6929',
 							'operator' => '==',
 							'value' => '1',
 						),
 					),
 				),
 				'wrapper' => array(
 					'width' => '',
 					'class' => '',
 					'id' => '',
 				),
 				'default_value' => '',
 			),
 		),
 		'location' => array(
 			array(
 				array(
 					'param' => 'post_type',
 					'operator' => '==',
 					'value' => 'hero_carousel_images',
 				),
 			),
 		),
 		'menu_order' => 0,
 		'position' => 'normal',
 		'style' => 'default',
 		'label_placement' => 'top',
 		'instruction_placement' => 'label',
 		'hide_on_screen' => '',
 		'active' => true,
 		'description' => '',
 	));

 	acf_add_local_field_group(array(
 		'key' => 'group_5eceadfc0f5a3',
 		'title' => 'Testimonials',
 		'fields' => array(
 			array(
 				'key' => 'field_5eceae0269f79',
 				'label' => 'testimonial_quote',
 				'name' => 'testimonial_quote',
 				'type' => 'textarea',
 				'instructions' => '',
 				'required' => 0,
 				'conditional_logic' => 0,
 				'wrapper' => array(
 					'width' => '',
 					'class' => '',
 					'id' => '',
 				),
 				'default_value' => '',
 				'placeholder' => '',
 				'maxlength' => '',
 				'rows' => '',
 				'new_lines' => '',
 			),
 			array(
 				'key' => 'field_5eceae3969f7a',
 				'label' => 'testimonial_author',
 				'name' => 'testimonial_author',
 				'type' => 'text',
 				'instructions' => '',
 				'required' => 0,
 				'conditional_logic' => 0,
 				'wrapper' => array(
 					'width' => '',
 					'class' => '',
 					'id' => '',
 				),
 				'default_value' => '',
 				'placeholder' => '',
 				'prepend' => '',
 				'append' => '',
 				'maxlength' => '',
 			),
 			array(
 				'key' => 'field_5eceae4269f7b',
 				'label' => 'description_of_work',
 				'name' => 'description_of_work',
 				'type' => 'text',
 				'instructions' => '',
 				'required' => 0,
 				'conditional_logic' => 0,
 				'wrapper' => array(
 					'width' => '',
 					'class' => '',
 					'id' => '',
 				),
 				'default_value' => '',
 				'placeholder' => '',
 				'prepend' => '',
 				'append' => '',
 				'maxlength' => '',
 			),
 			array(
 				'key' => 'field_5eceae4a69f7c',
 				'label' => 'testimonial_date',
 				'name' => 'testimonial_date',
 				'type' => 'text',
 				'instructions' => '',
 				'required' => 0,
 				'conditional_logic' => 0,
 				'wrapper' => array(
 					'width' => '',
 					'class' => '',
 					'id' => '',
 				),
 				'default_value' => '',
 				'placeholder' => '',
 				'prepend' => '',
 				'append' => '',
 				'maxlength' => '',
 			),
 			array(
 				'key' => 'field_5fa183ebcfb2d',
 				'label' => 'star_rating',
 				'name' => 'star_rating',
 				'type' => 'text',
 				'instructions' => '',
 				'required' => 0,
 				'conditional_logic' => 0,
 				'wrapper' => array(
 					'width' => '',
 					'class' => '',
 					'id' => '',
 				),
 				'default_value' => '',
 				'placeholder' => '',
 				'prepend' => '',
 				'append' => '',
 				'maxlength' => '',
 			),
 			array(
 				'key' => 'field_5eceae5469f7d',
 				'label' => 'overall',
 				'name' => 'overall',
 				'type' => 'text',
 				'instructions' => '',
 				'required' => 0,
 				'conditional_logic' => 0,
 				'wrapper' => array(
 					'width' => '',
 					'class' => '',
 					'id' => '',
 				),
 				'default_value' => 5,
 				'placeholder' => '',
 				'prepend' => '',
 				'append' => '',
 				'maxlength' => '',
 			),
 			array(
 				'key' => 'field_5ecee028c300a',
 				'label' => 'author_image',
 				'name' => 'author_image',
 				'type' => 'image',
 				'instructions' => '',
 				'required' => 0,
 				'conditional_logic' => 0,
 				'wrapper' => array(
 					'width' => '',
 					'class' => '',
 					'id' => '',
 				),
 				'return_format' => 'array',
 				'preview_size' => 'medium',
 				'library' => 'all',
 				'min_width' => '',
 				'min_height' => '',
 				'min_size' => '',
 				'max_width' => '',
 				'max_height' => '',
 				'max_size' => '',
 				'mime_types' => '',
 			),
 			array(
 				'key' => 'field_5fa183adc50f3',
 				'label' => 'testimonial_in_carousel',
 				'name' => 'testimonial_in_carousel',
 				'type' => 'true_false',
 				'instructions' => 'Select True if this testimonial is to be included in the Testimonial carousel on the home page etc.
 	If the testimonial is more than 200 characters, this should NOT be selected.',
 				'required' => 0,
 				'conditional_logic' => 0,
 				'wrapper' => array(
 					'width' => '',
 					'class' => '',
 					'id' => '',
 				),
 				'message' => '',
 				'default_value' => 0,
 				'ui' => 0,
 				'ui_on_text' => '',
 				'ui_off_text' => '',
 			),
 		),
 		'location' => array(
 			array(
 				array(
 					'param' => 'post_type',
 					'operator' => '==',
 					'value' => 'testimonial_quotes',
 				),
 			),
 		),
 		'menu_order' => 0,
 		'position' => 'normal',
 		'style' => 'default',
 		'label_placement' => 'top',
 		'instruction_placement' => 'label',
 		'hide_on_screen' => '',
 		'active' => true,
 		'description' => '',
 	));

 	endif;
